string texto, textoEducado, censura;

censura = "********";

Console.Write("O que você acha da saga Crepúsculo? ");
texto = Console.ReadLine()!; // Lendo e armazenando o que o usuário escrever

textoEducado = texto.Replace("chato", censura)
                    .Replace("chata", censura)
                    .Replace("bobo", censura)
                    .Replace("boba", censura)
                    .Replace("feio", censura)
                    .Replace("feia", censura)
                    .Replace("besta", censura)
                    .Replace("burra", censura)
                    .Replace("burro", censura)
                    .Replace("tantã", censura)
                    .Replace("tonta", censura)
                    .Replace("tonto", censura)
                    .Replace("boboca", censura)
                    .Replace("palerma", censura)
                    .Replace("paspalho", censura)
                    .Replace("paspalha", censura)
                    .Replace("panaca", censura)
                    .Replace("pentelho", censura)
                    .Replace("pentelha", censura)
                    .Replace("bocó", censura)
                    .Replace("lixo", censura)
                    .Replace("merda", censura)
                    .Replace("cu", censura)
                    .Replace("bosta", censura)
                    .Replace("caralho", censura)
                    .Replace("foda", censura)
                    .Replace("cacete", censura)
                    .Replace("desgraça", censura)
                    .Replace("capeta", censura)
                    .Replace("CHATO", censura)
                    .Replace("CHATA", censura)
                    .Replace("BOBO", censura)
                    .Replace("BOBA", censura)
                    .Replace("FEIO", censura)
                    .Replace("FEIA", censura)
                    .Replace("BESTA", censura)
                    .Replace("BURRA", censura)
                    .Replace("BURRO", censura)
                    .Replace("TANTÃ", censura)
                    .Replace("TONTA", censura)
                    .Replace("TONTO", censura)
                    .Replace("BOBOCA", censura)
                    .Replace("PALERMA", censura)
                    .Replace("PASPALHO", censura)
                    .Replace("PASPALHA", censura)
                    .Replace("PANACA", censura)
                    .Replace("PENTELHO", censura)
                    .Replace("PENTELHA", censura)
                    .Replace("BOCÓ", censura)
                    .Replace("LIXO", censura)
                    .Replace("MERDA", censura)
                    .Replace("CU", censura)
                    .Replace("BOSTA", censura)
                    .Replace("CARALHO", censura)
                    .Replace("FODA", censura)
                    .Replace("CACETE", censura)
                    .Replace("DESGRAÇA", censura)
                    .Replace("CAPETA", censura); // Censurando o texto armazenado

Console.WriteLine("");
Console.WriteLine("Eu sou uma criança educada. No seu lugar eu diria:");
Console.WriteLine(textoEducado); // Exibindo o texto censurado